apiVersion: v1
kind: Service
metadata:
  name: shared-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
    - port: 5432
      targetPort: 5432
