spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  config:
    import:
      - application-integration-test.yaml
      - optional:application-email-template-test.yaml # won't be present in prod code
