{{- if and .Values.enabled .Values.users }}
apiVersion: batch/v1
kind: Job
metadata:
  name: idam-user-importer
  labels:
    app.kubernetes.io/name: idam-user-importer
    app.kubernetes.io/instance: {{ .Release.Name }}-idam-user-importer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: idam-user-importer
      labels:
        app.kubernetes.io/name: idam-user-importer
    spec:
      containers:
        {{- $global := .Values.global -}}
        {{- range $index, $item := .Values.users }}
        - name: idam-user-importer-{{ $index }}
          image: hmctspublic.azurecr.io/hmcts/idam/utils:latest
          command: [ /scripts/create-user.sh ]
          args:
            - '{{ .email }}'
            - '{{ .forename | default "Forename" }}'
            - '{{ .surname | default "Surname" }}'
            - '{{ .password | default "Password12" }}'
            - '{{ .group }}'
            - '[{{ range $index, $item := .roles }}{{ if $index }},{{ end }}{{ printf "{\"code\":\"%s\"}" $item }}{{end}}]'
          env:
            - name: IDAM_API_URL
              value: http://idam-api
            - name: IDAM_ADMIN_USER
              value: {{ $global.adminUser }}
            - name: IDAM_ADMIN_PASSWORD
              value: {{ $global.adminPassword }}
          resources:
            requests:
              cpu: 125m
              memory: 8Mi
            limits:
              cpu: 250m
              memory: 16Mi
          imagePullPolicy: IfNotPresent
        {{- end }}
      restartPolicy: OnFailure
{{- end }}