apiVersion: v1
kind: Service
metadata:
  name: fr-am
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
    - name: ldap
      port: 1389
      targetPort: 1389
    - name: web
      port: 8080
      targetPort: 8080
