idam-service-importer:
  enabled: true
  services:
    - label: CCD
      clientID: ccd_gateway
      clientSecret: ccd_gateway_secret
      redirectURL: http://localhost:3451/oauth2redirect
    - label: fpl
      clientID: fpl
      clientSecret: OOOOOOOOOOOOOOOO
      redirectURL: https://localhost:9000/oauth2/callback

idam-role-importer:
  enabled: true
  roles:
    - id: ccd-import
    - id: caseworker
    - id: caseworker-publiclaw
    - id: caseworker-publiclaw-solicitor
    - id: caseworker-publiclaw-courtadmin
    - id: caseworker-publiclaw-cafcass
    - id: caseworker-publiclaw-gatekeeper
    - id: caseworker-publiclaw-judiciary
    - id: caseworker-publiclaw-systemupdate