dependencies:
  - name: java
    version: 2.17.2
    repository: '@hmctspublic'
  - name: ccd
    version: 4.2.3
    repository: '@hmctspublic'
    tags:
      - fpl-ccd-stack
  - name: idam-pr
    version: ~2.2.5
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr